# Use these variables to connect through bastion host
ansible_user: admin
ansible_ssh_common_args: -i vagrant -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i vagrant -W %h:%p -q admin@localhost -p 5222'

# Use these variables to connect directly to targets without bastion
#ansible_user: admin
#ansible_ssh_common_args: -i vagrant -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 