== Overview

Simple Ansible ssh demo using:

* Docker containers to rapidly spin up simulated bastion and target hosts
* Docker dynamic inventory plugin `community.docker.docker_containers`
* No `ssh.cfg`, since most customers do not have this option
* Using `ansible_ssh_common_args` inventory variable
* Bastion host, which is required to reach target hosts (host -> bastion -> targets)
* Target hosts (scalable for performance testing purposes)

You can also use this demo without a bastion host and just connect directly to target hosts. See `docker-compose.yml` for both possible scenarios and how to enable them.

=== Usage

The following instructions show how to spin up the containers and test Ansible connectivity.

[source,bash]
----
# Create the image first
docker build . -f Dockerfile.ubuntu -t ansible-ssh-server

# Startup containers and gradually scale up (otherwise you hit errors)
docker compose up -d
docker compose up --scale target=20 -d
docker compose up --scale target=40 -d
docker compose up --scale target=60 -d
docker compose up --scale target=80 -d
docker compose up --scale target=100 -d

# Perform Ansible connection tests
ansible-playbook playbook-ping.yml
ansible-playbook playbook-ping.yml --forks=20

# Prove that bastion is required to connect to targets
docker compose stop bastion
# Fails to connect since bastion is stopped
ansible-playbook playbook-ping.yml

# Destroy all containers
docker compose down
----

Other tips and tricks.

[source,bash]
----
# Ensure docker dynamic inventory plugin works
ansible-inventory -i docker.yml --list

# Ensure you can connect to targets using ping
ansible targets -m ping

# Get host IP address
ipconfig getifaddr en0

# Get IP of target container
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ansible_target_1

# Get publicized port for bastion node for ssh connection
docker port bastion

# Test direct SSH to bastion node
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i vagrant admin@localhost -p 5222
----

Performance testing tips

[source,bash]
----
# Connect to bastion host
ssh -i vagrant admin@localhost -p 5222
# Clear dmesg buffer
sudo dmesg -c
# Edit sshd configuration
sudo vi /etc/ssh/sshd_config
# Exit bastion
exit

# Run Ansible connection test using forks parameter
ansible-playbook playbook-ping.yml --forks 50

# Connect to bastion host
ssh -i vagrant admin@localhost -p 5222
# Check dmesg buffer for errors
sudo dmesg
# Check ssh logs for errors
?
----

=== Ansible examples

[source,bash]
----
# Run ping playbook against all hosts/containers
ansible-playbook playbook-ping.yml

# Run ping playbook against all hosts/containers using forks parameter for performance
ansible-playbook playbook-ping.yml --forks=10

----

=== Performance Testing Outcomes

This lab was created to actually test possible connection errors when attempting a high number of forks against a high number of targets. It was discovered that when using a bastion host and a high number of forks (35, for example) there were random connection errors (not the same targets). However, without the bastion host and going directly to targets no errors were ever seen - even when using high number of forks. The take away from this was that there is a huge demand on the bastion host's resources when all those connections are attempted at the same time. When the bastion host cannot keep up or grow fast enough to provide the resources (containers dynamically grow) needed, it caused connection errors. However, running the same playbook repeatedly resulted in eventually all connections successfully being established. This, however, is the result of using the ssh `ControlPersist` paramete that holds onto the successful connections established on the 1st and 2nd attempts until the 3rd attempt connects to all targets. 

Ultimately the importance and focus should be placed on the resources of the bastion host.

For further testing, notice in `docker-compose.yml` you can set the memory/cpu resource limits for the bastion host. Without limits set, we see random connection failures because Docker cannot keep up with the resource demands that Ansible places on it for establishing parallel ssh connections. With limitations set, these errors never happen because bastion host has enough resources to support the ssh connection request demands. 

See below parameters in the docker-compose.yml file.

[source,bash]
----
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
----


=== References

https://github.com/ansible-collections/community.docker/issues/193[docker_container inventory plugin not defaulting ip and port correctly when using ssh connection type]
https://github.com/hashicorp/vagrant/tree/master/keys[Vagrant Insecure Keypair]
https://docs.ansible.com/ansible-tower/latest/html/userguide/jobs.html#at-capacity-determination-and-job-impact[Ansible Tower Capacity Determination and Job Impact]
https://access.redhat.com/solutions/4706201[Ansible playbook fails with "Cannot allocate memory]
https://opensource.com/article/19/3/ansible-performance[Ansible performance: Revving up the engine and maintaining stability]
https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg[Ansible parameters using ansible.cfg]
https://access.redhat.com/solutions/54099[What is the maximum setting for MaxStartups in /etc/ssh/sshd_config?]
https://github.com/jsternberg/ansible-agent[Alternative SSH connection plugin]
https://linuxhint.com/ssh-maxsessions-configuration/[SSH MaxSessions Configuration]
https://github.com/ansible/ansible/issues/17349#issuecomment-396088877[The MaxStartups sshd tweaks]


=== Credits

Original code thanks to Tony Kay
Specific implementation/lab by John Wadleigh
