== Overview

Simple Ansible ssh demo using:

* Docker containers to rapidly spin up simulated bastion and target hosts
* Docker dynamic inventory plugin `community.docker.docker_containers`
* No `ssh.cfg`, since most customers do not have this option
* Using `ansible_ssh_common_args` inventory variable
* Bastion host, which is required to reach target hosts (host -> bastion -> targets)
* Target hosts (scalable for performance testing purposes)

You can also use this demo without a bastion host and just connect directly to target hosts. See `docker-compose.yml` for both possible scenarios and how to enable them.

=== Usage

The following instructions show how to spin up the containers and test Ansible connectivity.

[source,bash]
----
# Startup containers and gradually scale up (otherwise you hit errors)
docker compose up -d
docker compose up --scale target=20 -d
docker compose up --scale target=40 -d
docker compose up --scale target=60 -d
docker compose up --scale target=80 -d
docker compose up --scale target=100 -d

# Perform Ansible connection tests
ansible-playbook playbook-ping.yml
ansible-playbook playbook-ping.yml --forks=20

# Prove that bastion is required to connect to targets
docker compose stop bastion
# Fails to connect since bastion is stopped
ansible-playbook playbook-ping.yml

# Destroy all containers
docker compose down
----

Other tips and tricks.

[source,bash]
----
# Ensure docker dynamic inventory plugin works
ansible-inventory -i docker.yml --list

# Ensure you can connect to targets using ping
ansible targets -m ping

# Get host IP address
ipconfig getifaddr en0

# Get IP of target container
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ansible_target_1

# Get publicized port for bastion node for ssh connection
docker port bastion

# Test direct SSH to bastion node
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i vagrant admin@localhost -p 5222
----

Performance testing tips

[source,bash]
----
# Connect to bastion host
ssh -i vagrant admin@localhost -p 5222
# Clear dmesg buffer
sudo dmesg -c
# Edit sshd configuration
sudo vi /etc/ssh/sshd_config
# Exit bastion
exit

# Run Ansible connection test using forks parameter
ansible-playbook playbook-ping.yml --forks 50

# Connect to bastion host
ssh -i vagrant admin@localhost -p 5222
# Check dmesg buffer for errors
sudo dmesg
# Check ssh logs for errors
?
----

=== Ansible examples

[source,bash]
----
# Run ping playbook against all hosts/containers
ansible-playbook playbook-ping.yml

# Run ping playbook against all hosts/containers using forks parameter for performance
ansible-playbook playbook-ping.yml --forks=10

----

=== References

[docker_container inventory plugin not defaulting ip and port correctly when using ssh connection type](https://github.com/ansible-collections/community.docker/issues/193)

[Vagrant Insecure Keypair](https://github.com/hashicorp/vagrant/tree/master/keys)

=== Credits

Original code thanks to Tony Kay
Specific implementation/lab by John Wadleigh
