# community.docker.docker_containers – Ansible dynamic inventory plugin for Docker containers
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_containers_inventory.html
plugin: community.docker.docker_containers
connection_type: ssh
groups:
  targets: "'target' in docker_name"
  bastions: "'bastion' in docker_name"
  ansible-platform: "'aap' in docker_name"

# Compose variables to set host and port correctly
# docker_container inventory plugin not defaulting ip and port correctly when using ssh connection type
# https://github.com/ansible-collections/community.docker/issues/193
compose:
  ansible_ssh_host: ansible_ssh_host | default(docker_name[1:], true)
  ansible_ssh_port: ansible_ssh_port | default(22, true)