---
name: ansible
networks:
  default:
    name: example.com

# SCENARIO: Use these services when testing indirect connection with bastion host
services:
  bastion:
    image: ansible-ssh-server
    container_name: bastion
    hostname: bastion
    privileged: true
    ports:
      - "5222:22"
    # mem_limit: 512m
    # mem_reservation: 128M
    # cpus: 0.5

  target:
    image: ansible-ssh-server
    privileged: true
