
FROM registry.access.redhat.com/ubi8/ubi:8.1

ARG ssh_user=admin
ENV SSH_USER=${ssh_user}
ARG ssh_password=admin
ENV SSH_PASSWORD=${ssh_password}
ARG ssh_public_key_file=vagrant.pub
ENV SSH_PUBLIC_KEY_FILE=${ssh_public_key_file}

RUN yum -y update
RUN yum install -y openssh
# TODO: This line fails currently...
RUN yum install -y openssh-server
RUN yum install -y sudo

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 ${SSH_USER} 
RUN echo "${SSH_USER}:${SSH_PASSWORD}" | chpasswd
RUN mkdir /home/ubuntu/.ssh
RUN chown ${SSH_USER} /home/ubuntu/.ssh
RUN chmod 700 /home/ubuntu/.ssh
COPY ${SSH_PUBLIC_KEY_FILE} /home/ubuntu/.ssh/authorized_keys
RUN chmod 400 /home/ubuntu/.ssh/authorized_keys
RUN chown ${SSH_USER} /home/ubuntu/.ssh/authorized_keys

#RUN service ssh start
RUN systemctl start sshd

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]